### ISSUE TITLE
`seq_id` and `prev_seq_id` are not being setup for gateio

### ISSUE THREAD

**Issue by elyase** [soulmachine/crypto-crawler-rs#10]
seq_id and prev_seq_id are [not being setup for gateio](https://github.com/soulmachine/crypto-crawler-rs/blob/83815c677f93a84b30205e6ccff52b4c8797b530/crypto-msg-parser/src/exchanges/gate/gate_spot_current.rs#L212)

It should probably be `ws_msg.U` and `ws_msg.u` but not sure I understand the definition of `seq_id` and `prev_seq_id`.

[Gateio orderbook reference](https://www.gate.io/article/19776)

**Comment by soulmachine** [comment]
Each orderbook message should have a unique `seq_id` and have `prev_seq_id` pointing to its former message, by this way all orderbook messages are linked together in a singly linked list.

**Comment by soulmachine** [comment]
I checked multiple data samples from gateio, I'm going to set `ws_msg.u` to `seq_id` and `ws_msg.U-1` to `prev_seq_id`

**Comment by soulmachine** [comment]
Partially fixed gate by this commit https://github.com/soulmachine/crypto-crawler-rs/commit/cf9ae4e2ad15588957b9e4e53a3cdf1fddd14409

Due to lack of docs, I'm not able to fill `prev_seq_id` for all cases.
