### ISSUE TITLE
carbonbot: specify symbols

### ISSUE THREAD

**Issue by xermicus** [soulmachine/crypto-crawler-rs#2]
first I have to thank you so much for providing this awesome piece of software! it really backs me out <3

I'd like to be in more control of the symbols ingested by `carbonbot`, since blindly subscribing to everything an exchange provides generates a tremendous amount of data which I don't need. 

features I'd like implement:
* sort the symbols by CMC rank, then truncate to a user supplied length (= "top X symbols by CMC rank").
* filter the symbols by a list of user supplied substring matches (allows manual control)

These additional "configuration" parameters could be supplied as cmd args, env vars or via a config file, please let me know whatever works best for you. If you are interested I can open a pull-request.

**Comment by xermicus** [comment]
Hi @soulmachine 

Commit `b0b102b37449a765ecaa40bc8c7995cf69ca3a1b` this feature

**Comment by soulmachine** [comment]
This issue should be fixed now?
