### ISSUE TITLE
crawl more than one exchange?

### ISSUE THREAD

**Issue by elyase** [soulmachine/crypto-crawler-rs#8]
Hi thanks for the great library! I was wondering if there is some way to use `crypto_crawler::crawl_l2_event` but for several exchanges? (rust noobie)

**Comment by soulmachine** [comment]
The API `crawl_l2_event()` can crawl multiple trading pairs in a single exchange.

If you need to crawl data from multiple exchanges, you'll need to call `crawl_l2_event()` multiple times.

**Comment by elyase** [comment]
thanks
